//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.ReportaloWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reportaloWS.azurewebsites.net/", ConfigurationName="ReportaloWS.ReportaloSoap")]
    public interface ReportaloSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/RegisterUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RegisterUser(string user_email, string user_name, string user_lastname, string password, int category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string user_email, string user_name, string user_lastname, string password, int category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string user_email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync(string user_email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/LoadCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoadCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/LoadCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoadCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/LoadSubCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoadSubCategories(int category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/LoadSubCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoadSubCategoriesAsync(int category_id);
        
        // CODEGEN: Parameter 'photo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/CreateIssue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApplication4.ReportaloWS.CreateIssueResponse CreateIssue(WebApplication4.ReportaloWS.CreateIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/CreateIssue", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication4.ReportaloWS.CreateIssueResponse> CreateIssueAsync(WebApplication4.ReportaloWS.CreateIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/SearchIssueByDateCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchIssueByDateCategory(int category_id, System.DateTime date_from, System.DateTime date_to, int sub_category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reportaloWS.azurewebsites.net/SearchIssueByDateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchIssueByDateCategoryAsync(int category_id, System.DateTime date_from, System.DateTime date_to, int sub_category_id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateIssue", WrapperNamespace="http://reportaloWS.azurewebsites.net/", IsWrapped=true)]
    public partial class CreateIssueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=0)]
        public string user_email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=1)]
        public int sub_category_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=2)]
        public int status_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=3)]
        public string issue_desc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=4)]
        public string issue_action;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=5)]
        public string GIS;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] photo;
        
        public CreateIssueRequest() {
        }
        
        public CreateIssueRequest(string user_email, int sub_category_id, int status_id, string issue_desc, string issue_action, string GIS, byte[] photo) {
            this.user_email = user_email;
            this.sub_category_id = sub_category_id;
            this.status_id = status_id;
            this.issue_desc = issue_desc;
            this.issue_action = issue_action;
            this.GIS = GIS;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateIssueResponse", WrapperNamespace="http://reportaloWS.azurewebsites.net/", IsWrapped=true)]
    public partial class CreateIssueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://reportaloWS.azurewebsites.net/", Order=0)]
        public bool CreateIssueResult;
        
        public CreateIssueResponse() {
        }
        
        public CreateIssueResponse(bool CreateIssueResult) {
            this.CreateIssueResult = CreateIssueResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportaloSoapChannel : WebApplication4.ReportaloWS.ReportaloSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportaloSoapClient : System.ServiceModel.ClientBase<WebApplication4.ReportaloWS.ReportaloSoap>, WebApplication4.ReportaloWS.ReportaloSoap {
        
        public ReportaloSoapClient() {
        }
        
        public ReportaloSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportaloSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportaloSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportaloSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterUser(string user_email, string user_name, string user_lastname, string password, int category_id) {
            return base.Channel.RegisterUser(user_email, user_name, user_lastname, password, category_id);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string user_email, string user_name, string user_lastname, string password, int category_id) {
            return base.Channel.RegisterUserAsync(user_email, user_name, user_lastname, password, category_id);
        }
        
        public bool Login(string user_email, string password) {
            return base.Channel.Login(user_email, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string user_email, string password) {
            return base.Channel.LoginAsync(user_email, password);
        }
        
        public System.Data.DataSet LoadCategories() {
            return base.Channel.LoadCategories();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoadCategoriesAsync() {
            return base.Channel.LoadCategoriesAsync();
        }
        
        public System.Data.DataSet LoadSubCategories(int category_id) {
            return base.Channel.LoadSubCategories(category_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoadSubCategoriesAsync(int category_id) {
            return base.Channel.LoadSubCategoriesAsync(category_id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication4.ReportaloWS.CreateIssueResponse WebApplication4.ReportaloWS.ReportaloSoap.CreateIssue(WebApplication4.ReportaloWS.CreateIssueRequest request) {
            return base.Channel.CreateIssue(request);
        }
        
        public bool CreateIssue(string user_email, int sub_category_id, int status_id, string issue_desc, string issue_action, string GIS, byte[] photo) {
            WebApplication4.ReportaloWS.CreateIssueRequest inValue = new WebApplication4.ReportaloWS.CreateIssueRequest();
            inValue.user_email = user_email;
            inValue.sub_category_id = sub_category_id;
            inValue.status_id = status_id;
            inValue.issue_desc = issue_desc;
            inValue.issue_action = issue_action;
            inValue.GIS = GIS;
            inValue.photo = photo;
            WebApplication4.ReportaloWS.CreateIssueResponse retVal = ((WebApplication4.ReportaloWS.ReportaloSoap)(this)).CreateIssue(inValue);
            return retVal.CreateIssueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication4.ReportaloWS.CreateIssueResponse> WebApplication4.ReportaloWS.ReportaloSoap.CreateIssueAsync(WebApplication4.ReportaloWS.CreateIssueRequest request) {
            return base.Channel.CreateIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication4.ReportaloWS.CreateIssueResponse> CreateIssueAsync(string user_email, int sub_category_id, int status_id, string issue_desc, string issue_action, string GIS, byte[] photo) {
            WebApplication4.ReportaloWS.CreateIssueRequest inValue = new WebApplication4.ReportaloWS.CreateIssueRequest();
            inValue.user_email = user_email;
            inValue.sub_category_id = sub_category_id;
            inValue.status_id = status_id;
            inValue.issue_desc = issue_desc;
            inValue.issue_action = issue_action;
            inValue.GIS = GIS;
            inValue.photo = photo;
            return ((WebApplication4.ReportaloWS.ReportaloSoap)(this)).CreateIssueAsync(inValue);
        }
        
        public System.Data.DataSet SearchIssueByDateCategory(int category_id, System.DateTime date_from, System.DateTime date_to, int sub_category_id) {
            return base.Channel.SearchIssueByDateCategory(category_id, date_from, date_to, sub_category_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchIssueByDateCategoryAsync(int category_id, System.DateTime date_from, System.DateTime date_to, int sub_category_id) {
            return base.Channel.SearchIssueByDateCategoryAsync(category_id, date_from, date_to, sub_category_id);
        }
    }
}
